name: "Test workflow"
on:
  pull_request:
  push:
    tags:
      - v**
    branches:
      - main

jobs:
  test-contract:
    runs-on: ubuntu-20.04
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.10"]
    defaults:
      run:
        working-directory: ./contract
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - run: python3 --version
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: |
          black --check .
          flake8
          mypy .
      - name: Test
        run: pytest
  
  test-client:
    runs-on: ubuntu-20.04
    container: node:${{ matrix.node }}
    strategy:
      matrix:
        node: ["18"]
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - run: node --version && npm --version
      - name: Install node dependencies
        run: npm ci
      - name: Generate
        run: npm run generate
      - name: Type check
        run: npx tsc
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/build
